### ISSUE TITLE
Is it a typo in FLASH module?

### ISSUE THREAD

**Issue by marsggbo** [lucidrains/FLASH-pytorch#10]
The original code is below:
https://github.com/lucidrains/FLASH-pytorch/blob/edce0fd9a172e65d94844162fd7b31defa1e9fea/flash_pytorch/flash_pytorch.py#L338

Is that a typo? maybe the correct version is `n=x.shape[-2]` or set `g=self.group_size`

**Comment by lucidrains** [comment]
@marsggbo ohh yea, the einops equation isn't very clear

it should be `b (n g) d -> b n g d`, with `g = self.group_size` but otherwise it is correct
