### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'special'

### ISSUE THREAD

**Issue by bibo-msft** [lucidrains/FLASH-pytorch#12]
I have torch==1.7.0a0 installed, but when I ran `out = gau(x)`, there is an error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "MYPATH/work/venv/pytorch-rocm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "MYPATH/work/flash-pytorch/git-FLASH-pytorch/flash_pytorch/flash_pytorch.py", line 201, in forward
>     attn = self.attn_fn(sim / seq_len)
>   File "MYPATH/work/venv/pytorch-rocm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "MYPATH/work/flash-pytorch/git-FLASH-pytorch/flash_pytorch/flash_pytorch.py", line 131, in forward
>     return (1 + torch.special.erf((x - mu) / (std * math.sqrt(2)))) * 0.5
> AttributeError: module 'torch' has no attribute 'special'

It seems that torch.special is introduced in Pytorch 1.9.

**Comment by lucidrains** [comment]
@bibo-msft ah ok, i put in a quick fix, thanks!

**Comment by bibo-msft** [comment]
I [used `torch.erf` instead of `torch.special.erf`](https://pytorch.org/docs/stable/generated/torch.erf.html), and it works for me now with torch==1.7.0a0. There is no need to change the requirement to >1.9.

![image](https://github.com/lucidrains/FLASH-pytorch/assets/129240105/1ed020b1-7e08-4eb6-bfe0-ae15b3da6758)

I will let you know if there is further issues with my `torch==1.7.0a0`.
