### ISSUE TITLE
Laplace Activation Function Implementation

### ISSUE THREAD

**Issue by boweny-cerebras** [lucidrains/FLASH-pytorch#7]
Seems like the implementation on Laplace Activation deviates from what the paper described:
In the paper, I think it should write `std = 1 / math.sqrt(4 * math.pi)` instead of `std = math.sqrt(0.25 * math.pi)` as the former one is an approximation of relu^2

**Comment by lucidrains** [comment]
@boweny-cerebras thank you for reporting this! :man_facepalming:
